version: '3.7'

services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    networks:
      - jenkins_dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    expose:
      - "2375"
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
    user: root

  jenkins:
    container_name: jenkins
    build:  
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dind
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://dind:2375
    networks:
      - jenkins_dind
    user: root

networks:
  jenkins_dind:
    driver: bridge

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:

