version: '3'
services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    user: root
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
    networks:
      - jenkins
  
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    environment:
      DOCKER_HOST: "tcp://dind:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:

